language: rust
rust:
  - stable
  - beta
  - nightly
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
os: linux  # different CPU architectures are only supported on Linux
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace